"""Generate the Supabase service adapters from the maintained Apps Script sources.

Only module wiring changes. PostgreSQL transactions replace Apps Script locks.
Run with --check to detect drift; npm ci supplies the pinned formatter.
"""

from pathlib import Path
import re
import subprocess
import sys

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
SOURCE_DIRECTORY = REPOSITORY_ROOT / "apps-script"
TARGET_DIRECTORY = REPOSITORY_ROOT / "supabase/functions/sports-day-api"
FORMATTER = REPOSITORY_ROOT / "node_modules/.bin/prettier"
GENERATED_NOTICE = (
    "// Generated by supabase/scripts/sync_legacy_services.py; "
    "edit the Apps Script source.\n"
)


def format_javascript(filename, source):
    """Use the pinned project formatter for reproducible generated modules."""
    return subprocess.run(
        [str(FORMATTER), "--stdin-filepath", str(TARGET_DIRECTORY / filename)],
        input=source,
        text=True,
        capture_output=True,
        check=True,
        cwd=REPOSITORY_ROOT,
    ).stdout


def replace_service_references(source, service_names, current_service=None):
    """Route references to other services through their shared service registry."""
    for service_name in service_names:
        if service_name != current_service:
            source = re.sub(
                r"\b" + service_name + r"(?=\s*\.)",
                "services." + service_name,
                source,
            )
    return source


def build_outputs():
    """Build module contents without writing files or changing business rules."""
    service_names = sorted(path.stem for path in SOURCE_DIRECTORY.glob("*Service.js"))
    outputs = {}
    configuration = (SOURCE_DIRECTORY / "Config.js").read_text()
    configuration = configuration[
        configuration.index("const TABLES") : configuration.index("/**\n * Opens")
    ]
    outputs["constants.js"] = GENERATED_NOTICE + re.sub(
        r"^const ", "export const ", configuration, flags=re.MULTILINE
    )

    for service_name in service_names:
        source = (SOURCE_DIRECTORY / f"{service_name}.js").read_text()
        source = replace_service_references(source, service_names, service_name)
        constants = [
            name for name in ("TABLES", "EVENT_TYPES", "EVENT_STATUS")
            if re.search(r"\b" + name + r"\b", source)
        ]
        dependencies = [
            name for name in ("Database", "ServiceUtilities", "LockService", "services")
            if re.search(r"\b" + name + r"\b", source)
        ]
        constants_import = (
            f'import {{ {", ".join(constants)} }} from "../constants.js";\n'
            if constants
            else ""
        )
        factory_comment = (
            f"/** Create the {service_name} adapter with "
            "request-scoped dependencies. */\n"
        )
        factory_declaration = (
            f"export function create{service_name}"
            f"({{ {', '.join(dependencies)} }}) {{\n"
        )
        outputs[f"services/{service_name}.js"] = (
            GENERATED_NOTICE
            + constants_import
            + factory_comment
            + factory_declaration
            + source
            + f"\nreturn {service_name};\n}}\n"
        )

    routing = (SOURCE_DIRECTORY / "Api.js").read_text()
    routing = routing[
        routing.index("function handleRequest") :
        routing.index("/**\n * Returns JSON.")
    ]
    routing = routing.replace(
        "function handleRequest(request)",
        "export function dispatch(request, services, ServiceUtilities)",
    ).replace("return jsonResponse(response);", "return response;")
    outputs["dispatch.js"] = (
        GENERATED_NOTICE
        + 'import { APPLICATION_ACTIONS } from "./constants.js";\n'
        + "/** Route an authenticated request through the compatible event "
        "services. */\n"
        + replace_service_references(routing, service_names)
    )

    # Reuse the original response/validation helpers instead of maintaining copies.
    utilities = (SOURCE_DIRECTORY / "Utilities.js").read_text()
    outputs["utilities.js"] = (
        GENERATED_NOTICE
        + "/** Adapt the shared utilities to the server's identifier generator. */\n"
        + "export function createServiceUtilities(createIdentifier) {\n"
        + "const Utilities = { getUuid: createIdentifier };\n"
        + utilities + "\nreturn ServiceUtilities;\n}\n"
    )
    outputs["services.js"] = GENERATED_NOTICE + "\n".join(
        f'import {{ create{name} }} from "./services/{name}.js";'
        for name in service_names
    ) + '''
import { createServiceUtilities } from './utilities.js';

/** Create services sharing one repository and the request's transaction lock. */
export function createServices(
  Database,
  { uuid: createIdentifier = () => crypto.randomUUID() } = {},
) {
  const services = {};
  const ServiceUtilities = createServiceUtilities(createIdentifier);
  // The repository already holds the transaction lock; nested legacy locks are
  // intentionally empty so the original service workflow remains compatible.
  const LockService = {
    /** Return the lock interface expected by the retained service workflow. */
    getScriptLock: () => ({
      /** The request transaction has already acquired the advisory lock. */
      waitLock() {},
      /** PostgreSQL releases the advisory lock when the transaction finishes. */
      releaseLock() {},
    }),
  };
  const context = { Database, ServiceUtilities, LockService, services };
''' + "\n".join(
        f"  services.{name} = create{name}(context);" for name in service_names
    ) + "\n  return { services, ServiceUtilities };\n}\n"
    return outputs


def main():
    """Write generated files, or fail the check when any module has drifted."""
    if not FORMATTER.exists():
        raise SystemExit("Run npm ci before generating or checking service modules.")
    check_only = "--check" in sys.argv
    failed = False
    for filename, source in build_outputs().items():
        content = format_javascript(filename, source)
        destination = TARGET_DIRECTORY / filename
        if check_only:
            if not destination.exists() or destination.read_text() != content:
                print("Out of sync:", destination.relative_to(REPOSITORY_ROOT))
                failed = True
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(content)
    if failed:
        raise SystemExit(1)
    completion_message = (
        "Service adapters match their sources."
        if check_only
        else "Generated service adapters and router."
    )
    print(completion_message)


if __name__ == "__main__":
    main()
