// Generated by supabase/scripts/sync_legacy_services.py; edit the Apps Script source.
import { APPLICATION_ACTIONS } from './constants.js';
/** Route an authenticated request through the compatible event services. */
export function dispatch(request, services, ServiceUtilities) {
  let response;

  try {
    switch (request.action) {
      case APPLICATION_ACTIONS.GET_TEAMS:
        response = ServiceUtilities.success(services.TeamService.getAll());

        break;

      case APPLICATION_ACTIONS.GET_COMPETITORS:
        response = ServiceUtilities.success(
          services.CompetitorService.getAll(),
        );

        break;

      case APPLICATION_ACTIONS.GET_EVENTS:
        response = ServiceUtilities.success(services.EventService.getAll());

        break;

      case APPLICATION_ACTIONS.GET_POINT_PROFILE:
        response = ServiceUtilities.success(
          services.EventService.getPointProfile(
            request.payload.id || request.payload.ID,
          ),
        );

        break;

      case APPLICATION_ACTIONS.GET_POINT_PROFILES:
        response = ServiceUtilities.success(
          services.EventService.getPointProfiles(),
        );

        break;

      case APPLICATION_ACTIONS.CREATE_POINT_PROFILE:
        response = ServiceUtilities.success(
          services.PointProfileService.create(request.payload),
        );

        break;

      case APPLICATION_ACTIONS.UPDATE_POINT_PROFILE:
        response = ServiceUtilities.success(
          services.PointProfileService.update(request.payload),
        );

        break;

      case APPLICATION_ACTIONS.GET_MATCHES_FOR_EVENT:
        response = ServiceUtilities.success(
          services.EventService.getMatchesForEvent(
            request.payload.eventId || request.payload.EventID,
            request.payload.eventRunId || request.payload.EventRunID,
          ),
        );

        break;

      case APPLICATION_ACTIONS.CREATE_ROUND_ROBIN_FIXTURES:
        response = ServiceUtilities.success(
          services.EventService.createRoundRobinFixtures(
            request.payload.eventId || request.payload.EventID,
            request.payload.eventRunId || request.payload.EventRunID,
          ),
        );

        break;

      case APPLICATION_ACTIONS.CREATE_TOURNAMENT_FIXTURES:
        response = ServiceUtilities.success(
          services.EventService.createTournamentFixtures(
            request.payload.eventId || request.payload.EventID,
            request.payload.eventRunId || request.payload.EventRunID,
            request.payload.teamIds || request.payload.TeamIDs,
          ),
        );

        break;

      case APPLICATION_ACTIONS.UPDATE_MATCH_WINNER:
        response = ServiceUtilities.success(
          services.EventService.updateMatchWinner(
            request.payload.matchId || request.payload.ID,
            request.payload.winnerId || request.payload.WinnerID,
            request.payload.eventRunId || request.payload.EventRunID,
          ),
        );

        break;

      case APPLICATION_ACTIONS.GET_RACE_RESULTS_FOR_EVENT:
        response = ServiceUtilities.success(
          services.RaceService.getForEvent(
            request.payload.eventId || request.payload.EventID,
            request.payload.eventRunId || request.payload.EventRunID,
          ),
        );

        break;

      case APPLICATION_ACTIONS.START_RACE_EVENT:
        response = ServiceUtilities.success(
          services.RaceService.startEvent(
            request.payload.eventId || request.payload.EventID,
            request.payload.eventRunId || request.payload.EventRunID,
          ),
        );

        break;

      case APPLICATION_ACTIONS.SAVE_RACE_HEAT_WINNER:
        response = ServiceUtilities.success(
          services.RaceService.saveHeatWinner(
            request.payload.eventId || request.payload.EventID,
            request.payload.eventRunId || request.payload.EventRunID,
            request.payload.competitionGender ||
              request.payload.CompetitionGender,
            request.payload.teamId || request.payload.TeamID,
            request.payload.competitorId || request.payload.CompetitorID,
          ),
        );

        break;

      case APPLICATION_ACTIONS.SAVE_RACE_FINAL_POSITIONS:
        response = ServiceUtilities.success(
          services.RaceService.saveFinalPositions(
            request.payload.eventId || request.payload.EventID,
            request.payload.eventRunId || request.payload.EventRunID,
            request.payload.competitionGender ||
              request.payload.CompetitionGender,
            request.payload.positions || request.payload.Positions,
          ),
        );

        break;

      case APPLICATION_ACTIONS.GET_DOUBLE_TEAM_MATCH_FOR_EVENT:
        response = ServiceUtilities.success(
          services.DoubleTeamService.getForEvent(
            request.payload.eventId || request.payload.EventID,
            request.payload.eventRunId || request.payload.EventRunID,
          ),
        );

        break;

      case APPLICATION_ACTIONS.SAVE_DOUBLE_TEAM_PAIRING:
        response = ServiceUtilities.success(
          services.DoubleTeamService.savePairing(
            request.payload.eventId || request.payload.EventID,
            request.payload.eventRunId || request.payload.EventRunID,
            request.payload.side1TeamIds || request.payload.Side1TeamIDs,
          ),
        );

        break;

      case APPLICATION_ACTIONS.SAVE_DOUBLE_TEAM_WINNER:
        response = ServiceUtilities.success(
          services.DoubleTeamService.saveWinner(
            request.payload.eventId || request.payload.EventID,
            request.payload.eventRunId || request.payload.EventRunID,
            request.payload.winnerSide || request.payload.WinnerSide,
          ),
        );

        break;

      case APPLICATION_ACTIONS.GET_CURRENT_EVENT_RUN: {
        const currentEventRun = services.EventRunService.getCurrent(
          request.payload.eventId || request.payload.EventID,
        );

        response = ServiceUtilities.success(
          services.ResultService.addConfirmationStatus(currentEventRun),
        );

        break;
      }

      case APPLICATION_ACTIONS.RESET_EVENT:
        response = ServiceUtilities.success(
          services.EventRunService.reset(
            request.payload.eventId || request.payload.EventID,
            request.payload.currentEventRunId ||
              request.payload.CurrentEventRunID,
          ),
        );

        break;

      case APPLICATION_ACTIONS.GET_DISTANCE_RESULTS_FOR_EVENT_RUN:
        response = ServiceUtilities.success(
          services.DistanceService.getForEventRun(
            request.payload.eventId || request.payload.EventID,
            request.payload.eventRunId || request.payload.EventRunID,
          ),
        );

        break;

      case APPLICATION_ACTIONS.SAVE_DISTANCE_CATEGORY_POSITIONS:
        response = ServiceUtilities.success(
          services.DistanceService.saveCategoryPositions(
            request.payload.eventId || request.payload.EventID,
            request.payload.eventRunId || request.payload.EventRunID,
            request.payload.competitionGender ||
              request.payload.CompetitionGender,
            request.payload.positions || request.payload.Positions,
          ),
        );

        break;

      case APPLICATION_ACTIONS.COMPLETE_DISTANCE_EVENT_RUN:
        response = ServiceUtilities.success(
          services.DistanceService.completeEventRun(
            request.payload.eventId || request.payload.EventID,
            request.payload.eventRunId || request.payload.EventRunID,
          ),
        );

        break;

      case APPLICATION_ACTIONS.CONFIRM_EVENT_RESULTS:
        response = ServiceUtilities.success(
          services.ResultService.confirm(
            request.payload.eventId || request.payload.EventID,
            request.payload.eventRunId || request.payload.EventRunID,
          ),
        );

        break;

      case APPLICATION_ACTIONS.GET_LEADERBOARD:
        response = ServiceUtilities.success(services.LeaderboardService.get());

        break;

      case APPLICATION_ACTIONS.GET_EVENT_HISTORY:
        response = ServiceUtilities.success(
          services.EventHistoryService.get(
            request.payload.eventId || request.payload.EventID,
          ),
        );

        break;

      case APPLICATION_ACTIONS.CREATE_COMPETITOR:
        response = ServiceUtilities.success(
          services.CompetitorService.create(request.payload),
        );

        break;

      case APPLICATION_ACTIONS.UPDATE_COMPETITOR:
        response = ServiceUtilities.success(
          services.CompetitorService.update(request.payload),
        );

        break;

      default:
        response = ServiceUtilities.failure(
          'Unknown API action: ' + request.action,
        );
    }
  } catch (error) {
    response = ServiceUtilities.failure(error.message);
  }

  return response;
}
