// Generated by supabase/scripts/sync_legacy_services.py; edit the Apps Script source.
import { createCompetitorService } from './services/CompetitorService.js';
import { createDistanceService } from './services/DistanceService.js';
import { createDoubleTeamService } from './services/DoubleTeamService.js';
import { createEventHistoryService } from './services/EventHistoryService.js';
import { createEventRunService } from './services/EventRunService.js';
import { createEventService } from './services/EventService.js';
import { createLeaderboardService } from './services/LeaderboardService.js';
import { createPointProfileService } from './services/PointProfileService.js';
import { createRaceService } from './services/RaceService.js';
import { createResultService } from './services/ResultService.js';
import { createTeamService } from './services/TeamService.js';
import { createServiceUtilities } from './utilities.js';

/** Create services sharing one repository and the request's transaction lock. */
export function createServices(
  Database,
  { uuid: createIdentifier = () => crypto.randomUUID() } = {},
) {
  const services = {};
  const ServiceUtilities = createServiceUtilities(createIdentifier);
  // The repository already holds the transaction lock; nested legacy locks are
  // intentionally empty so the original service workflow remains compatible.
  const LockService = {
    /** Return the lock interface expected by the retained service workflow. */
    getScriptLock: () => ({
      /** The request transaction has already acquired the advisory lock. */
      waitLock() {},
      /** PostgreSQL releases the advisory lock when the transaction finishes. */
      releaseLock() {},
    }),
  };
  const context = { Database, ServiceUtilities, LockService, services };
  services.CompetitorService = createCompetitorService(context);
  services.DistanceService = createDistanceService(context);
  services.DoubleTeamService = createDoubleTeamService(context);
  services.EventHistoryService = createEventHistoryService(context);
  services.EventRunService = createEventRunService(context);
  services.EventService = createEventService(context);
  services.LeaderboardService = createLeaderboardService(context);
  services.PointProfileService = createPointProfileService(context);
  services.RaceService = createRaceService(context);
  services.ResultService = createResultService(context);
  services.TeamService = createTeamService(context);
  return { services, ServiceUtilities };
}
