-- Preserve Sheet insertion order where fixture generation and lists use it.
-- Production imports must supply source_order from the original Sheet row order.
alter table public.teams add column source_order bigint generated by default as identity unique;
alter table public.competitors add column source_order bigint generated by default as identity unique;
alter table public.point_profiles add column source_order bigint generated by default as identity unique;
alter table public.events add column source_order bigint generated by default as identity unique;
alter table public.event_runs add column source_order bigint generated by default as identity unique;
alter table public.event_competitors add column source_order bigint generated by default as identity unique;
alter table public.double_team_matches add column source_order bigint generated by default as identity unique;

-- Reordering four positions must validate the final state, not each interim row.
drop index public.race_results_run_category_position_idx;
alter table public.race_results add constraint race_results_run_category_position_key
    unique (event_run_id, competition_gender, final_position) deferrable initially deferred;
alter table public.distance_results drop constraint distance_results_run_category_position_key;
alter table public.distance_results add constraint distance_results_run_category_position_key
    unique (event_run_id, competition_gender, position) deferrable initially deferred;
