-- Group each annual competition so a new Sports Day never overwrites history.

create table public.sports_days (
    id text primary key,
    name text not null,
    is_active boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    source_order bigint generated by default as identity unique,
    constraint sports_days_id_not_blank check (btrim(id) <> ''),
    constraint sports_days_name_not_blank check (btrim(name) <> ''),
    constraint sports_days_name_length check (char_length(name) <= 80)
);

create unique index sports_days_name_case_insensitive_idx
    on public.sports_days (lower(btrim(name)));
create unique index sports_days_one_active_idx
    on public.sports_days (is_active)
    where is_active;

insert into public.sports_days (id, name, is_active)
values ('SPORTS_DAY_2026', 'SportsDay2026', true);

alter table public.teams add column sports_day_id text
    default 'SPORTS_DAY_2026' references public.sports_days(id);
alter table public.competitors add column sports_day_id text
    default 'SPORTS_DAY_2026' references public.sports_days(id);
alter table public.point_profiles add column sports_day_id text
    default 'SPORTS_DAY_2026' references public.sports_days(id);
alter table public.events add column sports_day_id text
    default 'SPORTS_DAY_2026' references public.sports_days(id);
alter table public.event_runs add column sports_day_id text
    default 'SPORTS_DAY_2026' references public.sports_days(id);
alter table public.results add column sports_day_id text
    default 'SPORTS_DAY_2026' references public.sports_days(id);
alter table public.matches add column sports_day_id text
    default 'SPORTS_DAY_2026' references public.sports_days(id);
alter table public.race_results add column sports_day_id text
    default 'SPORTS_DAY_2026' references public.sports_days(id);
alter table public.event_competitors add column sports_day_id text
    default 'SPORTS_DAY_2026' references public.sports_days(id);
alter table public.distance_results add column sports_day_id text
    default 'SPORTS_DAY_2026' references public.sports_days(id);
alter table public.double_team_matches add column sports_day_id text
    default 'SPORTS_DAY_2026' references public.sports_days(id);
alter table public.attempts add column sports_day_id text
    default 'SPORTS_DAY_2026' references public.sports_days(id);

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'teams', 'competitors', 'point_profiles', 'events', 'event_runs',
        'results', 'matches', 'race_results', 'event_competitors',
        'distance_results', 'double_team_matches', 'attempts'
    ] loop
        execute format(
            'alter table public.%I alter column sports_day_id set not null',
            table_name
        );
        execute format(
            'create index %I on public.%I (sports_day_id)',
            table_name || '_sports_day_id_idx',
            table_name
        );
    end loop;
end;
$$;

-- Composite keys prevent records from referring to teams, competitors, profiles,
-- events or runs belonging to another Sports Day.
alter table public.teams add constraint teams_sports_day_id_id_key
    unique (sports_day_id, id);
alter table public.competitors add constraint competitors_sports_day_id_id_key
    unique (sports_day_id, id);
alter table public.point_profiles add constraint point_profiles_sports_day_id_id_key
    unique (sports_day_id, id);
alter table public.events add constraint events_sports_day_id_id_key
    unique (sports_day_id, id);
alter table public.event_runs add constraint event_runs_sports_day_event_id_id_key
    unique (sports_day_id, event_id, id);

alter table public.competitors add constraint competitors_sports_day_team_fkey
    foreign key (sports_day_id, team_id)
    references public.teams(sports_day_id, id);
alter table public.events add constraint events_sports_day_profile_fkey
    foreign key (sports_day_id, point_profile_id)
    references public.point_profiles(sports_day_id, id);
alter table public.event_runs add constraint event_runs_sports_day_event_fkey
    foreign key (sports_day_id, event_id)
    references public.events(sports_day_id, id);
alter table public.results add constraint results_sports_day_run_fkey
    foreign key (sports_day_id, event_id, event_run_id)
    references public.event_runs(sports_day_id, event_id, id);
alter table public.results add constraint results_sports_day_team_fkey
    foreign key (sports_day_id, team_id)
    references public.teams(sports_day_id, id);
alter table public.matches add constraint matches_sports_day_run_fkey
    foreign key (sports_day_id, event_id, event_run_id)
    references public.event_runs(sports_day_id, event_id, id);
alter table public.matches add constraint matches_sports_day_team_1_fkey
    foreign key (sports_day_id, team_1_id)
    references public.teams(sports_day_id, id);
alter table public.matches add constraint matches_sports_day_team_2_fkey
    foreign key (sports_day_id, team_2_id)
    references public.teams(sports_day_id, id);
alter table public.matches add constraint matches_sports_day_winner_fkey
    foreign key (sports_day_id, winner_id)
    references public.teams(sports_day_id, id);
alter table public.race_results add constraint race_results_sports_day_run_fkey
    foreign key (sports_day_id, event_id, event_run_id)
    references public.event_runs(sports_day_id, event_id, id);
alter table public.race_results add constraint race_results_sports_day_team_fkey
    foreign key (sports_day_id, team_id)
    references public.teams(sports_day_id, id);
alter table public.race_results add constraint race_results_sports_day_competitor_fkey
    foreign key (sports_day_id, competitor_id)
    references public.competitors(sports_day_id, id);
alter table public.event_competitors add constraint event_competitors_sports_day_run_fkey
    foreign key (sports_day_id, event_id, event_run_id)
    references public.event_runs(sports_day_id, event_id, id);
alter table public.event_competitors add constraint event_competitors_sports_day_competitor_fkey
    foreign key (sports_day_id, competitor_id)
    references public.competitors(sports_day_id, id);
alter table public.distance_results add constraint distance_results_sports_day_run_fkey
    foreign key (sports_day_id, event_id, event_run_id)
    references public.event_runs(sports_day_id, event_id, id);
alter table public.distance_results add constraint distance_results_sports_day_team_fkey
    foreign key (sports_day_id, team_id)
    references public.teams(sports_day_id, id);
alter table public.double_team_matches add constraint double_team_matches_sports_day_run_fkey
    foreign key (sports_day_id, event_id, event_run_id)
    references public.event_runs(sports_day_id, event_id, id);
alter table public.double_team_matches add constraint double_team_matches_sports_day_team_1_fkey
    foreign key (sports_day_id, side_1_team_1_id)
    references public.teams(sports_day_id, id);
alter table public.double_team_matches add constraint double_team_matches_sports_day_team_2_fkey
    foreign key (sports_day_id, side_1_team_2_id)
    references public.teams(sports_day_id, id);
alter table public.double_team_matches add constraint double_team_matches_sports_day_team_3_fkey
    foreign key (sports_day_id, side_2_team_1_id)
    references public.teams(sports_day_id, id);
alter table public.double_team_matches add constraint double_team_matches_sports_day_team_4_fkey
    foreign key (sports_day_id, side_2_team_2_id)
    references public.teams(sports_day_id, id);
alter table public.attempts add constraint attempts_sports_day_run_fkey
    foreign key (sports_day_id, event_id, event_run_id)
    references public.event_runs(sports_day_id, event_id, id);
alter table public.attempts add constraint attempts_sports_day_competitor_fkey
    foreign key (sports_day_id, competitor_id)
    references public.competitors(sports_day_id, id);

alter table public.sports_days enable row level security;
grant select, insert, update, delete on public.sports_days to sports_day_api;
grant usage, select on sequence public.sports_days_source_order_seq
    to sports_day_api;
create policy sports_day_api_all on public.sports_days
    for all to sports_day_api using (true) with check (true);

create trigger sports_days_set_updated_at
before update on public.sports_days
for each row execute function public.set_updated_at();
