// Generated by supabase/scripts/sync_legacy_services.py; edit the Apps Script source.
import { TABLES, EVENT_TYPES, EVENT_STATUS } from '../constants.js';
/** Create the DistanceService adapter with request-scoped dependencies. */
export function createDistanceService({
  Database,
  ServiceUtilities,
  services,
}) {
  /**
   * ==========================================================
   * Sports Day Manager
   *
   * Distance Service
   *
   * Stores observed team placings for distance events.
   * ==========================================================
   */

  const DISTANCE_CATEGORIES = Object.freeze(['Male', 'Female']);

  const DistanceService = {
    /** Return distance placings and completion state for the current run. */
    getForEventRun(eventIdentifier, eventRunIdentifier) {
      this.getDistanceEvent(eventIdentifier);
      services.EventRunService.assertCurrent(
        eventIdentifier,
        eventRunIdentifier,
      );

      return {
        results: this.getResults(eventIdentifier, eventRunIdentifier),
        participantSelectionAvailable: Database.getHeaders(
          TABLES.DISTANCE_RESULTS,
        ).includes('CompetitorID'),
        competitors: this.getParticipantChoices(
          eventIdentifier,
          eventRunIdentifier,
        ),
      };
    },

    /** Validate and save every team placing for one distance category. */
    saveCategoryPositions(
      eventIdentifier,
      eventRunIdentifier,
      competitionGender,
      positions,
    ) {
      this.getDistanceEvent(eventIdentifier);

      const eventRun = services.EventRunService.assertCurrent(
        eventIdentifier,
        eventRunIdentifier,
      );

      this.validateCategory(competitionGender);

      const activeTeams = services.TeamService.getAll();

      this.validatePositions(activeTeams, positions);

      const results = this.getResults(eventIdentifier, eventRunIdentifier);

      if (
        results.some(
          (result) => !activeTeams.some((team) => team.ID === result.TeamID),
        )
      ) {
        throw new Error(
          'The active teams have changed since these placings were recorded. Restore the original teams or reset the event to start a new run.',
        );
      }

      const existingResults = results.filter(
        (result) => result.CompetitionGender === competitionGender,
      );

      const participantIdentifiers = positions.map((position) =>
        this.getParticipantIdentifier(
          position,
          competitionGender,
          existingResults,
        ),
      );

      positions.forEach((position, index) => {
        const teamIdentifier = position.teamId || position.TeamID;

        const finalPosition = Number(position.position || position.Position);

        const existing = existingResults.find(
          (result) => result.TeamID === teamIdentifier,
        );

        const result = {
          ID: existing ? existing.ID : ServiceUtilities.uuid(),

          EventID: eventIdentifier,

          EventRunID: eventRunIdentifier,

          CompetitionGender: competitionGender,

          TeamID: teamIdentifier,

          Position: finalPosition,
        };

        if (
          Database.getHeaders(TABLES.DISTANCE_RESULTS).includes('CompetitorID')
        ) {
          result.CompetitorID = participantIdentifiers[index];
        }

        if (existing) {
          if (!Database.update(TABLES.DISTANCE_RESULTS, existing.ID, result)) {
            throw new Error('Distance positions could not be updated.');
          }
        } else {
          Database.insert(TABLES.DISTANCE_RESULTS, result);
        }
      });

      // Corrections retain completion timestamps and do not create another run.
      if (eventRun.Status !== EVENT_STATUS.COMPLETE) {
        services.EventRunService.updateStatus(
          eventIdentifier,
          eventRunIdentifier,
          EVENT_STATUS.IN_PROGRESS,
        );
      }

      return this.getForEventRun(eventIdentifier, eventRunIdentifier);
    },

    /** Return active choices and retain previously selected competitors for corrections. */
    getParticipantChoices(eventIdentifier, eventRunIdentifier) {
      if (
        !Database.getHeaders(TABLES.DISTANCE_RESULTS).includes('CompetitorID')
      ) {
        return [];
      }
      const savedIdentifiers = this.getResults(
        eventIdentifier,
        eventRunIdentifier,
      ).map((result) => result.CompetitorID);
      return services.CompetitorService.getAll()
        .filter(
          (competitor) =>
            services.CompetitorService.isAvailableForEvents(competitor) ||
            savedIdentifiers.includes(competitor.ID),
        )
        .map((competitor) => ({
          ID: competitor.ID,
          Name: competitor.Name,
          TeamID: competitor.TeamID,
          CompetitionGender: competitor.CompetitionGender,
          Active: services.CompetitorService.isAvailableForEvents(competitor),
        }));
    },

    /** Validate an optional new choice while preserving a saved choice omitted by older clients. */
    getParticipantIdentifier(position, competitionGender, existingResults) {
      const teamIdentifier = position.teamId || position.TeamID;
      const existingIdentifier =
        existingResults.find((result) => result.TeamID === teamIdentifier)
          ?.CompetitorID || '';
      const supplied =
        Object.prototype.hasOwnProperty.call(position, 'competitorId') ||
        Object.prototype.hasOwnProperty.call(position, 'CompetitorID');
      const competitorIdentifier = supplied
        ? String(position.competitorId ?? position.CompetitorID ?? '').trim()
        : existingIdentifier;
      if (
        !competitorIdentifier ||
        competitorIdentifier === existingIdentifier
      ) {
        return competitorIdentifier;
      }
      const competitor =
        services.CompetitorService.getById(competitorIdentifier);
      if (
        !Database.getHeaders(TABLES.DISTANCE_RESULTS).includes(
          'CompetitorID',
        ) ||
        !competitor ||
        !services.CompetitorService.isAvailableForEvents(competitor) ||
        competitor.TeamID !== teamIdentifier ||
        competitor.CompetitionGender !== competitionGender
      ) {
        throw new Error(
          'Choose an available participant from this team and competition category, or leave the name blank.',
        );
      }
      return competitorIdentifier;
    },

    /** Complete the distance run only after all required placings exist. */
    completeEventRun(eventIdentifier, eventRunIdentifier) {
      this.getDistanceEvent(eventIdentifier);

      const eventRun = services.EventRunService.assertCurrent(
        eventIdentifier,
        eventRunIdentifier,
      );

      if (eventRun.Status === EVENT_STATUS.COMPLETE) {
        return this.getForEventRun(eventIdentifier, eventRunIdentifier);
      }

      const activeTeams = services.TeamService.getAll();

      const results = this.getResults(eventIdentifier, eventRunIdentifier);

      if (
        activeTeams.length !== 4 ||
        !DISTANCE_CATEGORIES.every((category) =>
          this.isCategoryComplete(
            activeTeams,
            results.filter((result) => result.CompetitionGender === category),
          ),
        )
      ) {
        throw new Error(
          'Save complete Male and Female team placings before completing the event.',
        );
      }

      services.EventRunService.updateStatus(
        eventIdentifier,
        eventRunIdentifier,
        EVENT_STATUS.COMPLETE,
      );

      return this.getForEventRun(eventIdentifier, eventRunIdentifier);
    },

    /** Read engine results belonging to this event and run. */
    getResults(eventIdentifier, eventRunIdentifier) {
      return Database.get(TABLES.DISTANCE_RESULTS).filter(
        (result) =>
          result.EventID === eventIdentifier &&
          result.EventRunID === eventRunIdentifier,
      );
    },

    /** Require an existing event with the distance format. */
    getDistanceEvent(eventIdentifier) {
      const event = services.EventService.getById(eventIdentifier);

      if (!event) {
        throw new Error('Event not found.');
      }

      if (event.EventType !== EVENT_TYPES.DISTANCE) {
        throw new Error('Event is not a distance competition.');
      }

      return event;
    },

    /** Reject competition categories unsupported by this event engine. */
    validateCategory(competitionGender) {
      if (!DISTANCE_CATEGORIES.includes(competitionGender)) {
        throw new Error('Distance category must be Male or Female.');
      }
    },

    /** Require one unique finishing position for each active team. */
    validatePositions(activeTeams, positions) {
      if (activeTeams.length !== 4) {
        throw new Error(
          'A distance competition requires exactly four active teams.',
        );
      }

      if (!Array.isArray(positions) || positions.length !== 4) {
        throw new Error('Assign all four team positions.');
      }

      const activeTeamIdentifiers = activeTeams.map((team) => team.ID);

      const teamIdentifiers = positions.map(
        (position) => position.teamId || position.TeamID,
      );

      const finalPositions = positions.map((position) =>
        Number(position.position || position.Position),
      );

      if (
        new Set(teamIdentifiers).size !== 4 ||
        !teamIdentifiers.every((teamIdentifier) =>
          activeTeamIdentifiers.includes(teamIdentifier),
        ) ||
        !activeTeamIdentifiers.every((teamIdentifier) =>
          teamIdentifiers.includes(teamIdentifier),
        )
      ) {
        throw new Error('Every active team must appear exactly once.');
      }

      if (
        new Set(finalPositions).size !== 4 ||
        !finalPositions.every(
          (position) =>
            Number.isInteger(position) && position >= 1 && position <= 4,
        )
      ) {
        throw new Error('Use each position from 1st to 4th exactly once.');
      }
    },

    /** Check that the category has every required finishing position. */
    isCategoryComplete(activeTeams, results) {
      const teamIdentifiers = results.map((result) => result.TeamID);

      const positions = results.map((result) => Number(result.Position));

      return (
        results.length === 4 &&
        new Set(teamIdentifiers).size === 4 &&
        activeTeams.every((team) => teamIdentifiers.includes(team.ID)) &&
        new Set(positions).size === 4 &&
        positions.every(
          (position) =>
            Number.isInteger(position) && position >= 1 && position <= 4,
        )
      );
    },
  };

  return DistanceService;
}
