// Generated by supabase/scripts/sync_legacy_services.py; edit the Apps Script source.
import { TABLES, EVENT_TYPES } from '../constants.js';
/** Create the EventHistoryService adapter with request-scoped dependencies. */
export function createEventHistoryService({
  Database,
  ServiceUtilities,
  services,
}) {
  /**
   * ==========================================================
   * Sports Day Manager
   *
   * Event History Service
   *
   * Reconstructs read-only event history from run-scoped data.
   * ==========================================================
   */

  const EventHistoryService = {
    /** Build read-only event history without altering stored results. */
    get(eventIdentifier) {
      const event = services.EventService.getById(eventIdentifier);

      if (!event) {
        throw new Error('Event not found.');
      }

      const runs = Database.get(TABLES.EVENT_RUNS)
        .filter((run) => run.EventID === eventIdentifier)
        .sort(
          (firstRecord, secondRecord) =>
            Number(secondRecord.RunNumber) - Number(firstRecord.RunNumber),
        );

      const teams = Database.get(TABLES.TEAMS);

      const competitors =
        event.EventType === EVENT_TYPES.HEAT_FINAL
          ? Database.get(TABLES.COMPETITORS)
          : [];

      const results = this.getEventRows(TABLES.RESULTS, eventIdentifier);

      const engineRows = this.getEngineRows(event, eventIdentifier);

      const teamsByIdentifier = services.LeaderboardService.indexById(teams);

      const competitorsByIdentifier =
        services.LeaderboardService.indexById(competitors);

      const resultsByRunIdentifier = this.groupByRunId(results);

      const engineRowsByRunIdentifier = this.groupByRunId(engineRows);

      const warnings = [];

      const runIdentifiers = new Set(runs.map((run) => run.ID));

      if (
        results.some((result) => ServiceUtilities.isBlank(result.EventRunID)) ||
        engineRows.some((row) => ServiceUtilities.isBlank(row.EventRunID))
      ) {
        warnings.push(
          'Some legacy rows have no EventRunID and cannot be assigned to a historical run.',
        );
      }

      if (
        results.some(
          (result) =>
            result.EventRunID && !runIdentifiers.has(result.EventRunID),
        ) ||
        engineRows.some(
          (row) => row.EventRunID && !runIdentifiers.has(row.EventRunID),
        )
      ) {
        warnings.push(
          'Some rows reference an unavailable Event Run and are not shown.',
        );
      }

      const profileState = this.getPointProfileState(event, results.length > 0);

      if (profileState.Warning) {
        warnings.push(profileState.Warning);
      }

      return {
        Event: {
          ID: event.ID,
          Name: event.Name,
          EventType: event.EventType,
          PointsProfileID: event.PointsProfileID,
        },

        Warnings: warnings,

        Runs: runs.map((run) =>
          this.buildRunSummary(
            run,
            event,
            engineRowsByRunIdentifier[run.ID] || [],
            resultsByRunIdentifier[run.ID] || [],
            teamsByIdentifier,
            competitorsByIdentifier,
            profileState,
          ),
        ),
      };
    },

    /** Read event-owned rows, allowing optional legacy tables to be absent. */
    getEventRows(tableName, eventIdentifier) {
      if (!Database.exists(tableName)) {
        return [];
      }

      return Database.get(tableName).filter(
        (row) => row.EventID === eventIdentifier,
      );
    },

    /** Select the engine table appropriate to this event format. */
    getEngineRows(event, eventIdentifier) {
      const tableByEventType = {
        [EVENT_TYPES.ROUND_ROBIN]: TABLES.MATCHES,
        [EVENT_TYPES.TOURNAMENT]: TABLES.MATCHES,
        [EVENT_TYPES.HEAT_FINAL]: TABLES.RACE_RESULTS,
        [EVENT_TYPES.DISTANCE]: TABLES.DISTANCE_RESULTS,
        [EVENT_TYPES.DOUBLE_TEAM]: TABLES.DOUBLE_TEAM_MATCHES,
      };

      const tableName = tableByEventType[event.EventType];

      return tableName ? this.getEventRows(tableName, eventIdentifier) : [];
    },

    /** Group records by run without mixing current and historical results. */
    groupByRunId(rows) {
      return rows.reduce((grouped, row) => {
        if (ServiceUtilities.isBlank(row.EventRunID)) {
          return grouped;
        }

        if (!grouped[row.EventRunID]) {
          grouped[row.EventRunID] = [];
        }

        grouped[row.EventRunID].push(row);

        return grouped;
      }, {});
    },

    /** Resolve and validate the point profile, retaining history warnings. */
    getPointProfileState(event, required) {
      if (!required) {
        return {
          Profile: null,
          Warning: '',
        };
      }

      if (!event.PointsProfileID) {
        return {
          Profile: null,
          Warning:
            'Points unavailable because this event has no point profile.',
        };
      }

      try {
        services.PointProfileService.ensureCurrentSchema();

        const matchingProfiles = Database.get(TABLES.POINT_PROFILES).filter(
          (profile) => profile.ID === event.PointsProfileID,
        );

        if (matchingProfiles.length !== 1) {
          return {
            Profile: null,
            Warning: `Points unavailable because point profile ${event.PointsProfileID} is missing or duplicated.`,
          };
        }

        return {
          Profile: services.PointProfileService.validateAndNormalise(
            matchingProfiles[0],
            true,
          ),
          Warning: '',
        };
      } catch (error) {
        return {
          Profile: null,
          Warning: `Points unavailable because this event's point profile is invalid: ${error.message}`,
        };
      }
    },

    /** Combine one run, its outcomes and its confirmed results for history. */
    buildRunSummary(
      run,
      event,
      engineRows,
      resultRows,
      teamsByIdentifier,
      competitorsByIdentifier,
      profileState,
    ) {
      const runWarnings = [];

      const categories = this.associateResultCategories(
        event.EventType,
        engineRows,
        resultRows,
      );

      const results = this.buildResults(
        event.EventType,
        resultRows,
        teamsByIdentifier,
        profileState.Profile,
        categories,
      );

      const outcomes = this.buildOutcomes(
        event.EventType,
        engineRows,
        teamsByIdentifier,
        competitorsByIdentifier,
        results,
        categories,
        runWarnings,
      );

      if (resultRows.length && profileState.Warning) {
        runWarnings.push(profileState.Warning);
      }

      return {
        ID: run.ID,

        EventID: run.EventID,

        RunNumber: Number(run.RunNumber),

        Status: run.Status || 'UNKNOWN',

        IsCurrent: services.EventRunService.isTrue(run.IsCurrent),

        ResetFromRunID: run.ResetFromRunID || '',

        StartedAt: run.StartedAt || '',

        CompletedAt: run.CompletedAt || '',

        ResultStatus: resultRows.length ? 'CONFIRMED' : 'NOT_CONFIRMED',

        ConfirmedResultCount: resultRows.length,

        Outcomes: outcomes,

        Results: results,

        Warnings: runWarnings,
      };
    },

    /** Decorate confirmed placings with team names and current-profile points. */
    buildResults(
      eventType,
      resultRows,
      teamsByIdentifier,
      profile,
      categories,
    ) {
      const roundRobinPoints =
        profile && eventType === EVENT_TYPES.ROUND_ROBIN
          ? services.LeaderboardService.getRoundRobinPointsByPosition(
              resultRows,
              profile,
            )
          : {};

      return resultRows
        .map((result, index) => {
          const team = teamsByIdentifier[result.TeamID] || null;

          const position = services.LeaderboardService.normalisePosition(
            result.Position,
          );

          const positionKey = position === null ? 'invalid' : String(position);

          let points = null;

          if (profile) {
            points =
              eventType === EVENT_TYPES.ROUND_ROBIN
                ? roundRobinPoints[positionKey]
                : services.LeaderboardService.getPointsForPosition(
                    profile,
                    result.Position,
                  );
          }

          return {
            ID: result.ID || '',
            TeamID: result.TeamID || '',
            TeamName: team ? team.Name : '',
            TeamColour: team ? team.Colour || '' : '',
            Position: position,
            Points: points,
            Category: categories ? categories[index] : '',
            Warning: team ? '' : 'Referenced team is unavailable.',
          };
        })
        .sort(
          (firstRecord, secondRecord) =>
            (firstRecord.Position === null
              ? Number.MAX_SAFE_INTEGER
              : firstRecord.Position) -
              (secondRecord.Position === null
                ? Number.MAX_SAFE_INTEGER
                : secondRecord.Position) ||
            String(firstRecord.TeamName).localeCompare(
              String(secondRecord.TeamName),
            ),
        );
    },

    /** Match confirmed placings to engine competition categories. */
    associateResultCategories(eventType, engineRows, resultRows) {
      if (
        ![EVENT_TYPES.HEAT_FINAL, EVENT_TYPES.DISTANCE].includes(eventType) ||
        !resultRows.length ||
        engineRows.length !== resultRows.length
      ) {
        return null;
      }

      const categories = [];

      for (let index = 0; index < resultRows.length; index++) {
        const engineRow = engineRows[index];

        const result = resultRows[index];

        const enginePosition =
          eventType === EVENT_TYPES.HEAT_FINAL
            ? engineRow.FinalPosition
            : engineRow.Position;

        if (
          !['Male', 'Female'].includes(engineRow.CompetitionGender) ||
          engineRow.TeamID !== result.TeamID ||
          Number(enginePosition) !== Number(result.Position)
        ) {
          return null;
        }

        categories.push(engineRow.CompetitionGender);
      }

      return categories;
    },

    /** Select the history builder for the event format. */
    buildOutcomes(
      eventType,
      engineRows,
      teamsByIdentifier,
      competitorsByIdentifier,
      results,
      categories,
      warnings,
    ) {
      switch (eventType) {
        case EVENT_TYPES.ROUND_ROBIN:
        case EVENT_TYPES.TOURNAMENT:
          return this.buildMatchOutcomes(
            eventType,
            engineRows,
            teamsByIdentifier,
          );

        case EVENT_TYPES.HEAT_FINAL:
          return this.buildRaceOutcomes(
            engineRows,
            teamsByIdentifier,
            competitorsByIdentifier,
            results,
            categories,
          );

        case EVENT_TYPES.DISTANCE:
          return this.buildDistanceOutcomes(
            engineRows,
            teamsByIdentifier,
            results,
            categories,
          );

        case EVENT_TYPES.DOUBLE_TEAM:
          return this.buildDoubleTeamOutcomes(
            engineRows,
            teamsByIdentifier,
            warnings,
          );

        default:
          return {
            Type: 'UNKNOWN',
            HasData: false,
          };
      }
    },

    /** Describe round-robin or tournament fixtures for read-only history. */
    buildMatchOutcomes(eventType, matches, teamsByIdentifier) {
      const orderedMatches = matches
        .map((match, index) => ({
          match,
          index,
        }))
        .sort(
          (firstRecord, secondRecord) =>
            Number(firstRecord.match.Round) -
              Number(secondRecord.match.Round) ||
            firstRecord.index - secondRecord.index,
        );

      let semiFinalNumber = 0;

      const summaries = orderedMatches.map((item) => {
        const match = item.match;

        let label = `Round ${match.Round || '?'}`;

        if (eventType === EVENT_TYPES.TOURNAMENT) {
          if (Number(match.Round) === 1) {
            semiFinalNumber++;

            label = `Semi-final ${semiFinalNumber}`;
          } else if (Number(match.Round) === 2) {
            label = 'Third-place playoff';
          } else if (Number(match.Round) === 3) {
            label = 'Final';
          }
        }

        const complete = services.ResultService.isCompletedMatch(match);

        return {
          Label: label,
          Team1: this.buildTeamReference(match.Team1ID, teamsByIdentifier),
          Team2: this.buildTeamReference(match.Team2ID, teamsByIdentifier),
          Winner: complete
            ? this.buildTeamReference(match.WinnerID, teamsByIdentifier)
            : null,
          Status: complete ? 'COMPLETE' : 'INCOMPLETE',
        };
      });

      const participantIdentifiers = [
        ...new Set(
          matches
            .flatMap((match) => [match.Team1ID, match.Team2ID])
            .filter(Boolean),
        ),
      ];

      return {
        Type: eventType,
        HasData: matches.length > 0,
        ParticipatingTeams: participantIdentifiers.map((teamIdentifier) =>
          this.buildTeamReference(teamIdentifier, teamsByIdentifier),
        ),
        Matches: summaries,
      };
    },

    /** Describe category finalists and finish positions for history. */
    buildRaceOutcomes(
      rows,
      teamsByIdentifier,
      competitorsByIdentifier,
      results,
      categories,
    ) {
      return {
        Type: EVENT_TYPES.HEAT_FINAL,
        HasData: rows.length > 0,
        ResultsCategorised: Boolean(categories),
        Categories: ['Male', 'Female'].map((category) => ({
          Name: category,
          Entries: rows
            .filter((row) => row.CompetitionGender === category)
            .map((row) => {
              const competitor =
                competitorsByIdentifier[row.CompetitorID] || null;

              return {
                Team: this.buildTeamReference(row.TeamID, teamsByIdentifier),
                CompetitorID: row.CompetitorID || '',
                CompetitorName: competitor ? competitor.Name : '',
                FinalPosition: services.LeaderboardService.normalisePosition(
                  row.FinalPosition,
                ),
                Warning: competitor
                  ? ''
                  : 'Referenced competitor is unavailable.',
              };
            })
            .sort(
              (firstRecord, secondRecord) =>
                (firstRecord.FinalPosition === null
                  ? Number.MAX_SAFE_INTEGER
                  : firstRecord.FinalPosition) -
                  (secondRecord.FinalPosition === null
                    ? Number.MAX_SAFE_INTEGER
                    : secondRecord.FinalPosition) ||
                String(firstRecord.Team.TeamName).localeCompare(
                  String(secondRecord.Team.TeamName),
                ),
            ),
          Results: categories
            ? results.filter((result) => result.Category === category)
            : [],
        })),
      };
    },

    /** Describe saved distance placings by competition category. */
    buildDistanceOutcomes(rows, teamsByIdentifier, results, categories) {
      return {
        Type: EVENT_TYPES.DISTANCE,
        HasData: rows.length > 0,
        ResultsCategorised: Boolean(categories),
        Categories: ['Male', 'Female'].map((category) => ({
          Name: category,
          Entries: rows
            .filter((row) => row.CompetitionGender === category)
            .map((row) => ({
              Team: this.buildTeamReference(row.TeamID, teamsByIdentifier),
              Position: services.LeaderboardService.normalisePosition(
                row.Position,
              ),
            }))
            .sort(
              (firstRecord, secondRecord) =>
                (firstRecord.Position === null
                  ? Number.MAX_SAFE_INTEGER
                  : firstRecord.Position) -
                  (secondRecord.Position === null
                    ? Number.MAX_SAFE_INTEGER
                    : secondRecord.Position) ||
                String(firstRecord.Team.TeamName).localeCompare(
                  String(secondRecord.Team.TeamName),
                ),
            ),
          Results: categories
            ? results.filter((result) => result.Category === category)
            : [],
        })),
      };
    },

    /** Describe paired teams and the winning side, retaining warnings. */
    buildDoubleTeamOutcomes(rows, teamsByIdentifier, warnings) {
      if (rows.length > 1) {
        warnings.push(
          'Multiple double-team fixtures were recorded for this run; all are shown.',
        );
      }

      return {
        Type: EVENT_TYPES.DOUBLE_TEAM,
        HasData: rows.length > 0,
        Fixtures: rows.map((row) => ({
          Side1: [
            this.buildTeamReference(row.Side1Team1ID, teamsByIdentifier),
            this.buildTeamReference(row.Side1Team2ID, teamsByIdentifier),
          ],
          Side2: [
            this.buildTeamReference(row.Side2Team1ID, teamsByIdentifier),
            this.buildTeamReference(row.Side2Team2ID, teamsByIdentifier),
          ],
          WinnerSide: [1, 2].includes(Number(row.WinnerSide))
            ? Number(row.WinnerSide)
            : null,
          Status:
            (row.Complete === true || row.Complete === 'TRUE') &&
            [1, 2].includes(Number(row.WinnerSide))
              ? 'COMPLETE'
              : 'INCOMPLETE',
        })),
      };
    },

    /** Resolve a team for history or mark its missing reference explicitly. */
    buildTeamReference(teamIdentifier, teamsByIdentifier) {
      const team = teamsByIdentifier[teamIdentifier] || null;

      return {
        TeamID: teamIdentifier || '',
        TeamName: team ? team.Name : '',
        TeamColour: team ? team.Colour || '' : '',
        Warning: team ? '' : 'Referenced team is unavailable.',
      };
    },
  };

  return EventHistoryService;
}
