// Generated by supabase/scripts/sync_legacy_services.py; edit the Apps Script source.
import { TABLES, EVENT_TYPES } from '../constants.js';
/** Create the LeaderboardService adapter with request-scoped dependencies. */
export function createLeaderboardService({
  Database,
  ServiceUtilities,
  services,
}) {
  /**
   * ==========================================================
   * Sports Day Manager
   *
   * Leaderboard Service
   *
   * Calculates current team totals from confirmed current runs.
   * ==========================================================
   */

  const LeaderboardService = {
    /**
     * Returns the organiser-facing live leaderboard.
     *
     * @returns {Object[]}
     */
    get() {
      const teams = Database.get(TABLES.TEAMS).filter((team) =>
        services.TeamService.isActive(team),
      );

      if (!teams.length) {
        return [];
      }

      const events = Database.get(TABLES.EVENTS);

      const eventRuns = Database.get(TABLES.EVENT_RUNS);

      const results = Database.get(TABLES.RESULTS);

      const teamsByIdentifier = this.indexById(teams);

      const eventsByIdentifier = this.indexById(events);

      const currentRunsByEventIdentifier =
        this.getCurrentRunsByEventId(eventRuns);

      const currentResultsByEventIdentifier = this.getCurrentResultsByEventId(
        results,
        teamsByIdentifier,
        eventsByIdentifier,
        currentRunsByEventIdentifier,
      );

      const currentEventIdentifiers = Object.keys(
        currentResultsByEventIdentifier,
      );

      let profilesByIdentifier = {};

      if (currentEventIdentifiers.length) {
        services.PointProfileService.ensureCurrentSchema();

        profilesByIdentifier = this.groupById(
          Database.get(TABLES.POINT_PROFILES),
        );
      }

      const totals = {};

      teams.forEach((team) => {
        totals[team.ID] = 0;
      });

      currentEventIdentifiers.forEach((eventIdentifier) => {
        const event = eventsByIdentifier[eventIdentifier];

        const matchingProfiles =
          profilesByIdentifier[event.PointsProfileID] || [];

        if (!matchingProfiles.length) {
          throw new Error(
            `Event ${event.Name || event.ID} references missing point profile ${event.PointsProfileID || '(blank)'}.`,
          );
        }

        if (matchingProfiles.length > 1) {
          throw new Error(
            `Event ${event.Name || event.ID} references duplicate point profile ${event.PointsProfileID}.`,
          );
        }

        let profile;

        try {
          profile = services.PointProfileService.validateAndNormalise(
            matchingProfiles[0],
            true,
          );
        } catch (error) {
          throw new Error(
            `Event ${event.Name || event.ID} has an invalid point profile: ${error.message}`,
          );
        }

        const eventResults = currentResultsByEventIdentifier[eventIdentifier];

        if (event.EventType === EVENT_TYPES.ROUND_ROBIN) {
          this.addRoundRobinPoints(totals, eventResults, profile);

          return;
        }

        eventResults.forEach((result) => {
          totals[result.TeamID] += this.getPointsForPosition(
            profile,
            result.Position,
          );
        });
      });

      const leaderboard = teams
        .map((team) => ({
          Position: 0,

          TeamID: team.ID,

          TeamName: team.Name,

          TeamColour: team.Colour || '',

          Points: totals[team.ID],
        }))
        .sort(
          (firstRecord, secondRecord) =>
            secondRecord.Points - firstRecord.Points ||
            String(firstRecord.TeamName).localeCompare(
              String(secondRecord.TeamName),
            ),
        );

      this.assignCompetitionPositions(leaderboard);

      return leaderboard;
    },

    /** Index records by stable identifier for repeated lookups. */
    indexById(records) {
      return records.reduce((lookup, record) => {
        if (record.ID) {
          lookup[record.ID] = record;
        }

        return lookup;
      }, {});
    },

    /** Group records by identifier so duplicate references remain detectable. */
    groupById(records) {
      return records.reduce((lookup, record) => {
        if (!record.ID) {
          return lookup;
        }

        if (!lookup[record.ID]) {
          lookup[record.ID] = [];
        }

        lookup[record.ID].push(record);

        return lookup;
      }, {});
    },

    /** Find and validate the single current run for each event. */
    getCurrentRunsByEventId(eventRuns) {
      const currentRunsByEventIdentifier = {};

      const invalidEventIdentifiers = {};

      eventRuns.forEach((run) => {
        if (!services.EventRunService.isTrue(run.IsCurrent)) {
          return;
        }

        if (invalidEventIdentifiers[run.EventID]) {
          return;
        }

        if (currentRunsByEventIdentifier[run.EventID]) {
          delete currentRunsByEventIdentifier[run.EventID];

          invalidEventIdentifiers[run.EventID] = true;

          return;
        }

        currentRunsByEventIdentifier[run.EventID] = run;
      });

      return currentRunsByEventIdentifier;
    },

    /** Exclude historical runs when grouping official event results. */
    getCurrentResultsByEventId(
      results,
      teamsByIdentifier,
      eventsByIdentifier,
      currentRunsByEventIdentifier,
    ) {
      return results.reduce((grouped, result) => {
        const event = eventsByIdentifier[result.EventID];

        const currentRun = currentRunsByEventIdentifier[result.EventID];

        if (
          !teamsByIdentifier[result.TeamID] ||
          !event ||
          !currentRun ||
          !result.EventRunID ||
          result.EventRunID !== currentRun.ID
        ) {
          return grouped;
        }

        if (!grouped[result.EventID]) {
          grouped[result.EventID] = [];
        }

        grouped[result.EventID].push(result);

        return grouped;
      }, {});
    },

    /** Add tied round-robin awards to the affected team totals. */
    addRoundRobinPoints(totals, results, profile) {
      const pointsByPosition = this.getRoundRobinPointsByPosition(
        results,
        profile,
      );

      results.forEach((result) => {
        const position = this.normalisePosition(result.Position);

        const key = position === null ? 'invalid' : String(position);

        totals[result.TeamID] += pointsByPosition[key];
      });
    },

    /** Average occupied-place points and round up for tied standings. */
    getRoundRobinPointsByPosition(results, profile) {
      const resultsByPosition = {};

      results.forEach((result) => {
        const position = this.normalisePosition(result.Position);

        const key = position === null ? 'invalid' : String(position);

        if (!resultsByPosition[key]) {
          resultsByPosition[key] = [];
        }

        resultsByPosition[key].push(result);
      });

      return Object.keys(resultsByPosition).reduce((pointsByPosition, key) => {
        const group = resultsByPosition[key];

        const position = key === 'invalid' ? null : Number(key);

        let points = 0;

        if (position !== null) {
          const occupiedPoints = group.map((result, index) =>
            this.getPointsForPosition(profile, position + index),
          );

          points = Math.ceil(
            occupiedPoints.reduce((total, value) => total + value, 0) /
              group.length,
          );
        }

        pointsByPosition[key] = points;

        return pointsByPosition;
      }, {});
    },

    /** Look up the profile award for a placing, defaulting beyond fourth to zero. */
    getPointsForPosition(profile, position) {
      const fields = {
        1: 'First',
        2: 'Second',
        3: 'Third',
        4: 'Fourth',
      };

      const normalisedPosition = this.normalisePosition(position);

      if (normalisedPosition === null || !fields[normalisedPosition]) {
        return 0;
      }

      return profile[fields[normalisedPosition]];
    },

    /** Require a positive integer placing before calculating points. */
    normalisePosition(position) {
      if (ServiceUtilities.isBlank(position)) {
        return null;
      }

      const numericPosition = Number(position);

      return Number.isInteger(numericPosition) && numericPosition >= 1
        ? numericPosition
        : null;
    },

    /** Give equal totals equal ranks and skip the occupied positions. */
    assignCompetitionPositions(leaderboard) {
      let previousPoints = null;

      let previousPosition = 0;

      leaderboard.forEach((team, index) => {
        if (previousPoints === null || team.Points !== previousPoints) {
          previousPosition = index + 1;
        }

        team.Position = previousPosition;

        previousPoints = team.Points;
      });
    },
  };

  return LeaderboardService;
}
