// Generated by supabase/scripts/sync_legacy_services.py; edit the Apps Script source.
import { TABLES, EVENT_TYPES, EVENT_STATUS } from '../constants.js';
/** Create the RaceService adapter with request-scoped dependencies. */
export function createRaceService({ Database, ServiceUtilities, services }) {
  /**
   * ==========================================================
   * Sports Day Manager
   *
   * Race Service
   *
   * Handles heats and final race business logic.
   * ==========================================================
   */

  const RACE_CATEGORIES = Object.freeze(['Male', 'Female']);

  const RaceService = {
    /**
     * Returns persistent race results and eligible competitors.
     *
     * @param {string} eventIdentifier
     * @returns {Object}
     */
    getForEvent(eventIdentifier, eventRunIdentifier) {
      this.getRaceEvent(eventIdentifier);
      services.EventRunService.assertCurrent(
        eventIdentifier,
        eventRunIdentifier,
      );

      const eventMappings = this.getEventMappings(
        eventIdentifier,
        eventRunIdentifier,
      );

      return {
        results: this.getResults(eventIdentifier, eventRunIdentifier),

        eligibleCompetitors: this.getEligibleCompetitors(
          eventIdentifier,
          eventRunIdentifier,
          eventMappings,
        ),

        entrantsExplicit: eventMappings.length > 0,

        entrantCount: eventMappings.length,
      };
    },

    /**
     * Adds all currently available competitors to this event's
     * explicit entrant list without duplicating existing mappings.
     *
     * @param {string} eventIdentifier
     * @returns {Object}
     */
    startEvent(eventIdentifier, eventRunIdentifier) {
      this.getRaceEvent(eventIdentifier);
      services.EventRunService.assertCurrent(
        eventIdentifier,
        eventRunIdentifier,
      );

      const competitors = services.CompetitorService.getPresent();

      if (!competitors.length) {
        throw new Error(
          'No active or present competitors are available to add.',
        );
      }

      const mappings = this.getEventMappings(
        eventIdentifier,
        eventRunIdentifier,
      );

      const mappedCompetitorIdentifiers = mappings.map(
        (mapping) => mapping.CompetitorID,
      );

      competitors.forEach((competitor) => {
        if (!mappedCompetitorIdentifiers.includes(competitor.ID)) {
          Database.insert(TABLES.EVENT_COMPETITORS, {
            EventID: eventIdentifier,
            EventRunID: eventRunIdentifier,
            CompetitorID: competitor.ID,
          });

          mappedCompetitorIdentifiers.push(competitor.ID);
        }
      });

      return this.getForEvent(eventIdentifier, eventRunIdentifier);
    },

    /**
     * Saves or replaces one team's heat winner.
     *
     * @param {string} eventIdentifier
     * @param {string} competitionGender
     * @param {string} teamIdentifier
     * @param {string} competitorIdentifier
     * @returns {Object}
     */
    saveHeatWinner(
      eventIdentifier,
      eventRunIdentifier,
      competitionGender,
      teamIdentifier,
      competitorIdentifier,
    ) {
      this.getRaceEvent(eventIdentifier);
      services.EventRunService.assertCurrent(
        eventIdentifier,
        eventRunIdentifier,
      );
      this.validateCategory(competitionGender);

      const team = services.TeamService.getById(teamIdentifier);

      if (!team || !services.TeamService.isActive(team)) {
        throw new Error('Please choose an active team.');
      }

      const categoryResults = this.getResults(
        eventIdentifier,
        eventRunIdentifier,
      ).filter((result) => result.CompetitionGender === competitionGender);

      if (this.isCategoryComplete(categoryResults)) {
        throw new Error(
          'Heat winners cannot be changed after final positions have been recorded.',
        );
      }

      const competitor = this.getEligibleCompetitors(
        eventIdentifier,
        eventRunIdentifier,
      ).find((item) => item.ID === competitorIdentifier);

      if (!competitor) {
        throw new Error('Please choose an eligible competitor.');
      }

      if (competitor.TeamID !== teamIdentifier) {
        throw new Error('The competitor does not belong to the selected team.');
      }

      if (competitor.CompetitionGender !== competitionGender) {
        throw new Error(
          'The competitor is not eligible for this race category.',
        );
      }

      const existing = categoryResults.find(
        (result) => result.TeamID === teamIdentifier,
      );

      let raceResult;

      if (existing) {
        raceResult = Object.assign({}, existing, {
          CompetitorID: competitorIdentifier,
          FinalPosition: '',
        });

        if (!Database.update(TABLES.RACE_RESULTS, existing.ID, raceResult)) {
          throw new Error('The heat winner could not be updated.');
        }
      } else {
        raceResult = {
          ID: ServiceUtilities.uuid(),

          EventID: eventIdentifier,

          EventRunID: eventRunIdentifier,

          CompetitionGender: competitionGender,

          TeamID: teamIdentifier,

          CompetitorID: competitorIdentifier,

          FinalPosition: '',
        };

        Database.insert(TABLES.RACE_RESULTS, raceResult);
      }

      this.updateEventStatus(eventIdentifier, eventRunIdentifier);

      return this.getForEvent(eventIdentifier, eventRunIdentifier);
    },

    /**
     * Saves positions for the four selected finalists.
     *
     * @param {string} eventIdentifier
     * @param {string} competitionGender
     * @param {Object[]} positions
     * @returns {Object}
     */
    saveFinalPositions(
      eventIdentifier,
      eventRunIdentifier,
      competitionGender,
      positions,
    ) {
      this.getRaceEvent(eventIdentifier);
      services.EventRunService.assertCurrent(
        eventIdentifier,
        eventRunIdentifier,
      );
      this.validateCategory(competitionGender);

      const activeTeams = services.TeamService.getAll();

      const finalists = this.getResults(
        eventIdentifier,
        eventRunIdentifier,
      ).filter((result) => result.CompetitionGender === competitionGender);

      if (
        activeTeams.length !== 4 ||
        finalists.length !== activeTeams.length ||
        !activeTeams.every((team) =>
          finalists.some((result) => result.TeamID === team.ID),
        )
      ) {
        throw new Error(
          'Select one heat winner for every active team before completing the final.',
        );
      }

      if (!Array.isArray(positions) || positions.length !== 4) {
        throw new Error('Assign all four final positions.');
      }

      const competitorIdentifiers = positions.map(
        (position) => position.competitorId || position.CompetitorID,
      );

      const finalPositions = positions.map((position) =>
        Number(position.finalPosition || position.FinalPosition),
      );

      const finalistIdentifiers = finalists.map(
        (result) => result.CompetitorID,
      );

      if (
        new Set(competitorIdentifiers).size !== 4 ||
        !competitorIdentifiers.every((competitorIdentifier) =>
          finalistIdentifiers.includes(competitorIdentifier),
        ) ||
        !finalistIdentifiers.every((competitorIdentifier) =>
          competitorIdentifiers.includes(competitorIdentifier),
        )
      ) {
        throw new Error('Each selected finalist must appear exactly once.');
      }

      if (
        new Set(finalPositions).size !== 4 ||
        !finalPositions.every(
          (position) =>
            Number.isInteger(position) && position >= 1 && position <= 4,
        )
      ) {
        throw new Error(
          'Use each final position from 1st to 4th exactly once.',
        );
      }

      positions.forEach((position) => {
        const competitorIdentifier =
          position.competitorId || position.CompetitorID;

        const finalist = finalists.find(
          (result) => result.CompetitorID === competitorIdentifier,
        );

        const updatedResult = Object.assign({}, finalist, {
          FinalPosition: Number(
            position.finalPosition || position.FinalPosition,
          ),
        });

        if (!Database.update(TABLES.RACE_RESULTS, finalist.ID, updatedResult)) {
          throw new Error('Final positions could not be saved.');
        }
      });

      this.updateEventStatus(eventIdentifier, eventRunIdentifier);

      return this.getForEvent(eventIdentifier, eventRunIdentifier);
    },

    /** Require an existing event with the heat-and-final format. */
    getRaceEvent(eventIdentifier) {
      const event = services.EventService.getById(eventIdentifier);

      if (!event) {
        throw new Error('Event not found.');
      }

      if (event.EventType !== EVENT_TYPES.HEAT_FINAL) {
        throw new Error('Event is not a heats and final event.');
      }

      return event;
    },

    /** Reject competition categories unsupported by this event engine. */
    validateCategory(competitionGender) {
      if (!RACE_CATEGORIES.includes(competitionGender)) {
        throw new Error('Race category must be Male or Female.');
      }
    },

    /** Read engine results belonging to this event and run. */
    getResults(eventIdentifier, eventRunIdentifier) {
      return Database.get(TABLES.RACE_RESULTS).filter(
        (result) =>
          result.EventID === eventIdentifier &&
          result.EventRunID === eventRunIdentifier,
      );
    },

    /** Read the competitors explicitly entered in this event run. */
    getEventMappings(eventIdentifier, eventRunIdentifier) {
      return Database.get(TABLES.EVENT_COMPETITORS).filter(
        (mapping) =>
          mapping.EventID === eventIdentifier &&
          mapping.EventRunID === eventRunIdentifier,
      );
    },

    /** Resolve explicit entrants or the legacy active-competitor fallback. */
    getEligibleCompetitors(
      eventIdentifier,
      eventRunIdentifier,
      eventMappings = null,
    ) {
      const mappings =
        eventMappings ||
        this.getEventMappings(eventIdentifier, eventRunIdentifier);

      const mappedCompetitorIdentifiers = mappings.map(
        (mapping) => mapping.CompetitorID,
      );

      return services.CompetitorService.getPresent().filter(
        (competitor) =>
          !mappings.length ||
          mappedCompetitorIdentifiers.includes(competitor.ID),
      );
    },

    /** Check that the category has every required finishing position. */
    isCategoryComplete(results) {
      return (
        results.length === 4 &&
        new Set(results.map((result) => result.TeamID)).size === 4 &&
        new Set(results.map((result) => result.CompetitorID)).size === 4 &&
        results.every(
          (result) =>
            !ServiceUtilities.isBlank(result.FinalPosition) &&
            Number.isInteger(Number(result.FinalPosition)) &&
            Number(result.FinalPosition) >= 1 &&
            Number(result.FinalPosition) <= 4,
        ) &&
        new Set(results.map((result) => Number(result.FinalPosition))).size ===
          4
      );
    },

    /** Recalculate run completion from the saved category results. */
    updateEventStatus(eventIdentifier, eventRunIdentifier) {
      const results = this.getResults(eventIdentifier, eventRunIdentifier);

      const complete = RACE_CATEGORIES.every((category) =>
        this.isCategoryComplete(
          results.filter((result) => result.CompetitionGender === category),
        ),
      );

      const status = complete
        ? EVENT_STATUS.COMPLETE
        : EVENT_STATUS.IN_PROGRESS;

      services.EventRunService.updateStatus(
        eventIdentifier,
        eventRunIdentifier,
        status,
      );
    },
  };

  return RaceService;
}
