// Generated by supabase/scripts/sync_legacy_services.py; edit the Apps Script source.
import { TABLES, EVENT_TYPES, EVENT_STATUS } from '../constants.js';
/** Create the ResultService adapter with request-scoped dependencies. */
export function createResultService({
  Database,
  ServiceUtilities,
  LockService,
  services,
}) {
  /**
   * ==========================================================
   * Sports Day Manager
   *
   * Result Service
   *
   * Confirms completed event-run placings and snapshots points.
   * ==========================================================
   */

  const ResultService = {
    /** Decorate a run with the existence and count of official results. */
    addConfirmationStatus(eventRun) {
      const resultCount = this.getResultsForRun(eventRun.ID).length;

      return Object.assign({}, eventRun, {
        ResultsConfirmed: resultCount > 0,
        ConfirmedResultCount: resultCount,
      });
    },

    /** Replace official placings for the completed current run atomically. */
    confirm(eventIdentifier, eventRunIdentifier) {
      services.PointProfileService.ensureCurrentSchema();

      const lock = LockService.getScriptLock();

      lock.waitLock(30000);

      try {
        const event = services.EventService.getById(eventIdentifier);

        if (!event) {
          throw new Error('Event not found.');
        }

        const eventRun = services.EventRunService.assertCurrent(
          eventIdentifier,
          eventRunIdentifier,
        );

        if (eventRun.Status !== EVENT_STATUS.COMPLETE) {
          throw new Error(
            'Results can only be confirmed after the current event run is complete.',
          );
        }

        const pointProfile = this.getValidatedPointProfile(event);

        const resultPlacings = this.extractPlacings(
          event,
          eventRunIdentifier,
          pointProfile,
        );

        if (!resultPlacings.length) {
          throw new Error(
            'The completed event did not produce any team placings.',
          );
        }

        const existingResults = this.getResultsForRun(eventRunIdentifier);

        Database.removeWhere(
          TABLES.RESULTS,
          (result) => result.EventRunID === eventRunIdentifier,
        );

        const results = resultPlacings.map((placing) => {
          const result = {
            ID: ServiceUtilities.uuid(),

            EventID: eventIdentifier,

            EventRunID: eventRunIdentifier,

            TeamID: placing.TeamID,

            Position: placing.Position,

            PointsAwarded: Object.prototype.hasOwnProperty.call(
              placing,
              'PointsAwarded',
            )
              ? placing.PointsAwarded
              : this.getPointsForPosition(pointProfile, placing.Position),
          };

          Database.insert(TABLES.RESULTS, result);

          return result;
        });

        return {
          confirmed: true,

          replaced: existingResults.length > 0,

          resultCount: results.length,

          results,

          message: existingResults.length
            ? 'Confirmed results updated.'
            : 'Results confirmed.',
        };
      } finally {
        lock.releaseLock();
      }
    },

    /** Read official results belonging to exactly one run. */
    getResultsForRun(eventRunIdentifier) {
      return Database.get(TABLES.RESULTS).filter(
        (result) => result.EventRunID === eventRunIdentifier,
      );
    },

    /** Require a complete integer point profile before confirmation. */
    getValidatedPointProfile(event) {
      if (!event.PointsProfileID) {
        throw new Error('The event does not have a point profile.');
      }

      const profile = services.EventService.getPointProfile(
        event.PointsProfileID,
      );

      if (!profile) {
        throw new Error("The event's point profile was not found.");
      }

      return {
        1: profile.First,
        2: profile.Second,
        3: profile.Third,
        4: profile.Fourth,
      };
    },

    /** Look up the profile award for a placing, defaulting beyond fourth to zero. */
    getPointsForPosition(pointProfile, position) {
      return Object.prototype.hasOwnProperty.call(pointProfile, position)
        ? pointProfile[position]
        : 0;
    },

    /** Dispatch to the placing calculation for this event format. */
    extractPlacings(event, eventRunIdentifier, pointProfile) {
      switch (event.EventType) {
        case EVENT_TYPES.ROUND_ROBIN:
          return this.extractRoundRobinPlacings(
            event.ID,
            eventRunIdentifier,
            pointProfile,
          );

        case EVENT_TYPES.TOURNAMENT:
          return this.extractTournamentPlacings(event.ID, eventRunIdentifier);

        case EVENT_TYPES.HEAT_FINAL:
          return this.extractRacePlacings(event.ID, eventRunIdentifier);

        case EVENT_TYPES.DISTANCE:
          return this.extractDistancePlacings(event.ID, eventRunIdentifier);

        case EVENT_TYPES.DOUBLE_TEAM:
          return this.extractDoubleTeamPlacings(event.ID, eventRunIdentifier);

        default:
          throw new Error(
            'This event type does not support result confirmation.',
          );
      }
    },

    /** Rank wins and share occupied-place awards between tied teams. */
    extractRoundRobinPlacings(
      eventIdentifier,
      eventRunIdentifier,
      pointProfile,
    ) {
      const matches = services.EventService.getMatchesForEvent(
        eventIdentifier,
        eventRunIdentifier,
      );

      if (
        !matches.length ||
        !matches.every((match) => this.isCompletedMatch(match))
      ) {
        throw new Error(
          'Every round robin match must be complete before confirming results.',
        );
      }

      const teamIdentifiers = [
        ...new Set(matches.flatMap((match) => [match.Team1ID, match.Team2ID])),
      ];

      const standings = teamIdentifiers
        .map((teamIdentifier) => ({
          TeamID: teamIdentifier,
          TeamName:
            services.TeamService.getById(teamIdentifier)?.Name ||
            teamIdentifier,
          Wins: matches.filter((match) => match.WinnerID === teamIdentifier)
            .length,
        }))
        .sort(
          (firstRecord, secondRecord) =>
            secondRecord.Wins - firstRecord.Wins ||
            firstRecord.TeamName.localeCompare(secondRecord.TeamName),
        );

      const placings = [];

      let index = 0;

      while (index < standings.length) {
        const group = standings.filter(
          (team) => team.Wins === standings[index].Wins,
        );

        const position = index + 1;

        const occupiedPoints = group.map((team, groupIndex) =>
          this.getPointsForPosition(pointProfile, position + groupIndex),
        );

        const sharedPoints = Math.ceil(
          occupiedPoints.reduce((total, points) => total + points, 0) /
            group.length,
        );

        group.forEach((team) => {
          placings.push({
            TeamID: team.TeamID,
            Position: position,
            PointsAwarded: sharedPoints,
          });
        });

        index += group.length;
      }

      return placings;
    },

    /** Validate bracket progression and derive the four final placings. */
    extractTournamentPlacings(eventIdentifier, eventRunIdentifier) {
      const matches = services.EventService.getMatchesForEvent(
        eventIdentifier,
        eventRunIdentifier,
      );

      const semiFinals = matches.filter((match) => Number(match.Round) === 1);

      const thirdPlace = matches.find((match) => Number(match.Round) === 2);

      const finalMatch = matches.find((match) => Number(match.Round) === 3);

      if (
        matches.length !== 4 ||
        semiFinals.length !== 2 ||
        !thirdPlace ||
        !finalMatch ||
        !matches.every((match) => this.isCompletedMatch(match))
      ) {
        throw new Error(
          'The tournament must have two completed semi-finals, a completed third-place playoff and a completed final.',
        );
      }

      const semiFinalWinners = semiFinals.map((match) => match.WinnerID);

      const semiFinalLosers = semiFinals.map((match) =>
        this.getMatchLoser(match),
      );

      const semiFinalTeams = semiFinals.flatMap((match) => [
        match.Team1ID,
        match.Team2ID,
      ]);

      if (
        new Set(semiFinalTeams).size !== 4 ||
        !this.hasSameMembers(
          [finalMatch.Team1ID, finalMatch.Team2ID],
          semiFinalWinners,
        ) ||
        !this.hasSameMembers(
          [thirdPlace.Team1ID, thirdPlace.Team2ID],
          semiFinalLosers,
        )
      ) {
        throw new Error(
          'Tournament progression matches are inconsistent with the semi-final results.',
        );
      }

      return [
        { TeamID: finalMatch.WinnerID, Position: 1 },
        { TeamID: this.getMatchLoser(finalMatch), Position: 2 },
        { TeamID: thirdPlace.WinnerID, Position: 3 },
        { TeamID: this.getMatchLoser(thirdPlace), Position: 4 },
      ];
    },

    /** Build team placings from each category’s completed race final. */
    extractRacePlacings(eventIdentifier, eventRunIdentifier) {
      const results = services.RaceService.getResults(
        eventIdentifier,
        eventRunIdentifier,
      );

      if (
        !['Male', 'Female'].every((category) =>
          services.RaceService.isCategoryComplete(
            results.filter((result) => result.CompetitionGender === category),
          ),
        )
      ) {
        throw new Error(
          'Both race categories must have complete final positions.',
        );
      }

      return results
        .filter((result) =>
          ['Male', 'Female'].includes(result.CompetitionGender),
        )
        .map((result) => ({
          TeamID: result.TeamID,
          Position: Number(result.FinalPosition),
        }));
    },

    /** Build team placings from the completed distance categories. */
    extractDistancePlacings(eventIdentifier, eventRunIdentifier) {
      const results = services.DistanceService.getResults(
        eventIdentifier,
        eventRunIdentifier,
      );

      const activeTeams = services.TeamService.getAll();

      if (
        activeTeams.length !== 4 ||
        !['Male', 'Female'].every((category) =>
          services.DistanceService.isCategoryComplete(
            activeTeams,
            results.filter((result) => result.CompetitionGender === category),
          ),
        )
      ) {
        throw new Error(
          'Both distance categories must have complete team positions.',
        );
      }

      return results
        .filter((result) =>
          ['Male', 'Female'].includes(result.CompetitionGender),
        )
        .map((result) => ({
          TeamID: result.TeamID,
          Position: Number(result.Position),
        }));
    },

    /** Award the full winning or losing placing to both teammates. */
    extractDoubleTeamPlacings(eventIdentifier, eventRunIdentifier) {
      const match = services.DoubleTeamService.getForEvent(
        eventIdentifier,
        eventRunIdentifier,
      );

      if (
        !match ||
        !(match.Complete === true || match.Complete === 'TRUE') ||
        ![1, 2].includes(Number(match.WinnerSide))
      ) {
        throw new Error(
          'The double-team fixture must have a valid winning side.',
        );
      }

      const side1 = [match.Side1Team1ID, match.Side1Team2ID];

      const side2 = [match.Side2Team1ID, match.Side2Team2ID];

      if (new Set([...side1, ...side2]).size !== 4) {
        throw new Error(
          'The double-team fixture does not contain four unique teams.',
        );
      }

      const winningSide = Number(match.WinnerSide) === 1 ? side1 : side2;

      const losingSide = Number(match.WinnerSide) === 1 ? side2 : side1;

      return [
        ...winningSide.map((teamIdentifier) => ({
          TeamID: teamIdentifier,
          Position: 1,
        })),
        ...losingSide.map((teamIdentifier) => ({
          TeamID: teamIdentifier,
          Position: 2,
        })),
      ];
    },

    /** Require a completed match with a valid participating winner. */
    isCompletedMatch(match) {
      return (
        (match.Complete === true || match.Complete === 'TRUE') &&
        Boolean(match.Team1ID) &&
        Boolean(match.Team2ID) &&
        (match.WinnerID === match.Team1ID || match.WinnerID === match.Team2ID)
      );
    },

    /** Return the other participant in a match with a recorded winner. */
    getMatchLoser(match) {
      return match.WinnerID === match.Team1ID ? match.Team2ID : match.Team1ID;
    },

    /** Compare participant sets without depending on pairing order. */
    hasSameMembers(first, second) {
      return (
        first.length === second.length &&
        first.every((item) => second.includes(item)) &&
        new Set(first).size === first.length &&
        new Set(second).size === second.length
      );
    },
  };

  return ResultService;
}
