// Generated by supabase/scripts/sync_legacy_services.py; edit the Apps Script source.
import { TABLES } from '../constants.js';
/** Create the TeamService adapter with request-scoped dependencies. */
export function createTeamService({ Database, ServiceUtilities }) {
  /**
   * ==========================================================
   * Sports Day Manager
   *
   * Team Service
   *
   * Handles team-related business logic.
   * ==========================================================
   */

  const TeamService = {
    /**
     * Returns all active teams.
     *
     * @returns {Object[]}
     */
    getAll() {
      return Database.get(TABLES.TEAMS).filter((team) => this.isActive(team));
    },

    /**
     * Returns a team by ID.
     *
     * @param {string} identifier
     * @returns {Object|null}
     */
    getById(identifier) {
      return Database.findById(TABLES.TEAMS, identifier);
    },

    /**
     * Returns true if a team should be shown.
     *
     * @param {Object} team
     * @returns {boolean}
     */
    isActive(team) {
      if (!Object.prototype.hasOwnProperty.call(team, 'Active')) {
        return true;
      }

      if (ServiceUtilities.isBlank(team.Active)) {
        return true;
      }

      return team.Active === true || team.Active === 'TRUE';
    },
  };

  return TeamService;
}
